# Site settings
title: 'Albert Gonzalez'
description: 'A hunting we will go...'
url: 'http://hunt.revrse.sh/'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
#disqus_shortname: 'albgnz'

author:
  name: 'Albert Gonzalez'
  email: albertg@cerveau.us
  #twitter_username: albgnz
  facebook_username: albgnz
  github_username:  agonzal
  linkedin_username:  albgon

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

mermaid:
  src: js/mermaid.js


plugins: ['jekyll-paginate', "jekyll-mermaid"]
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
